#
# CLRDKSTown -- A custom plugin for the CLRDKS Town server.
# Hi there!
#

# Disable the vanilla pickaxe recipes to force players into using the tier system (default: true)
disable-pickaxe-recipes: true

# Should items tagged as non-droppable be allowed to be placed in enderchests (default: true)
drop-to-enderchests: true